android {
    sourceSets {
        google {
            java.srcDirs += ['src/google/java']
            res.srcDirs += ['src/google/res']
        }
    }
}

dependencies {
    // Google version use google fonts, otherwise bundle fonts
    //noinspection UseTomlInstead
    googleImplementation 'androidx.compose.ui:ui-text-google-fonts:1.10.5'


    // Similar thing to whats going on below, theese plugins are only meant to be on an :app module so we just check if the thing its being applied to has android.applicaiton
    if (project.plugins.hasPlugin("com.android.application")) {
        googleImplementation platform('com.google.fire' + 'base:fire' + 'base-bom:34.8.0')
        googleImplementation 'com.google.fire' + 'base:fire' + 'base-analytics'
        googleImplementation 'com.google.fire' + 'base:fire' + 'base-crash' + 'lytics'
        googleImplementation 'com.google.fire' + 'base:fire' + 'base-perf'
        googleImplementation 'com.google.fire' + 'base:fire' + 'base-messaging:25.0.1'
        //noinspection UseTomlInstead
        googleImplementation 'com.google.android.gms:play-services-location:21.3.0'
        //noinspection UseTomlInstead
        googleImplementation 'com.squareup.okhttp3:okhttp:5.3.2'
    }
    println(">>> [Google.gradle] Imported the google deps because this is a google build. (Or it could be a sync, for some reason its fine that if the google stuff is in a foss sync cuz its not in the build.)")
}

// This is the stuff that should only be added to the :app module so we check it first
// It also checks if we are in the google variant before adding it
// We allow it if its an IDE sync also because android studio gives syntax errors and this is just he easiest way to combat that
def taskNames = gradle.startParameter.taskNames
def isGoogleVariant = taskNames.any { it.toLowerCase().contains("google") }
def isIdeSync = System.getProperty("idea.sync.active") == "true"
def isApp = project.plugins.hasPlugin("com.android.application")
if ((isGoogleVariant || isIdeSync) && isApp) {
    apply plugin: 'com.google.gms.google-services'
    apply plugin: 'com.google.firebase.crashlytics'
}